using System;
using System.Collections.Generic;


namespace yamvu.ViewGeneration.HtmlNodes;

public static class Methods {
   // like this:  https://github.com/codechem/CC.CSX?tab=readme-ov-file

   public static HtmlNode A           (params IReadOnlyList<HtmlNode> contents) => new HtmlTag(contents, "a"           , CanSelfClose: false);
   public static HtmlNode Abbr        (params IReadOnlyList<HtmlNode> contents) => new HtmlTag(contents, "abbr"        , CanSelfClose: false);
   public static HtmlNode Address     (params IReadOnlyList<HtmlNode> contents) => new HtmlTag(contents, "address"     , CanSelfClose: false);
   public static HtmlNode Area        (params IReadOnlyList<HtmlNode> contents) => new HtmlTag(contents, "area"        , CanSelfClose: true );
   public static HtmlNode Article     (params IReadOnlyList<HtmlNode> contents) => new HtmlTag(contents, "article"     , CanSelfClose: false);
   public static HtmlNode Aside       (params IReadOnlyList<HtmlNode> contents) => new HtmlTag(contents, "aside"       , CanSelfClose: false);
   public static HtmlNode Audio       (params IReadOnlyList<HtmlNode> contents) => new HtmlTag(contents, "audio"       , CanSelfClose: false);
   public static HtmlNode B           (params IReadOnlyList<HtmlNode> contents) => new HtmlTag(contents, "b"           , CanSelfClose: false);
   public static HtmlNode Base        (params IReadOnlyList<HtmlNode> contents) => new HtmlTag(contents, "base"        , CanSelfClose: true );
   public static HtmlNode Bdi         (params IReadOnlyList<HtmlNode> contents) => new HtmlTag(contents, "bdi"         , CanSelfClose: false);
   public static HtmlNode Bdo         (params IReadOnlyList<HtmlNode> contents) => new HtmlTag(contents, "bdo"         , CanSelfClose: false);
   public static HtmlNode Blockquote  (params IReadOnlyList<HtmlNode> contents) => new HtmlTag(contents, "blockquote"  , CanSelfClose: false);
   public static HtmlNode Body        (params IReadOnlyList<HtmlNode> contents) => new HtmlTag(contents, "body"        , CanSelfClose: false);
   public static HtmlNode Br          (params IReadOnlyList<HtmlNode> contents) => new HtmlTag(contents, "br"          , CanSelfClose: true );
   public static HtmlNode Button      (params IReadOnlyList<HtmlNode> contents) => new HtmlTag(contents, "button"      , CanSelfClose: false);
   public static HtmlNode Canvas      (params IReadOnlyList<HtmlNode> contents) => new HtmlTag(contents, "canvas"      , CanSelfClose: false);
   public static HtmlNode Caption     (params IReadOnlyList<HtmlNode> contents) => new HtmlTag(contents, "caption"     , CanSelfClose: false);
   public static HtmlNode Cite        (params IReadOnlyList<HtmlNode> contents) => new HtmlTag(contents, "cite"        , CanSelfClose: false);
   public static HtmlNode Code        (params IReadOnlyList<HtmlNode> contents) => new HtmlTag(contents, "code"        , CanSelfClose: false);
   public static HtmlNode Col         (params IReadOnlyList<HtmlNode> contents) => new HtmlTag(contents, "col"         , CanSelfClose: true );
   public static HtmlNode Colgroup    (params IReadOnlyList<HtmlNode> contents) => new HtmlTag(contents, "colgroup"    , CanSelfClose: false);
   public static HtmlNode Data        (params IReadOnlyList<HtmlNode> contents) => new HtmlTag(contents, "data"        , CanSelfClose: false);
   public static HtmlNode Datalist    (params IReadOnlyList<HtmlNode> contents) => new HtmlTag(contents, "datalist"    , CanSelfClose: false);
   public static HtmlNode Dd          (params IReadOnlyList<HtmlNode> contents) => new HtmlTag(contents, "dd"          , CanSelfClose: false);
   public static HtmlNode Del         (params IReadOnlyList<HtmlNode> contents) => new HtmlTag(contents, "del"         , CanSelfClose: false);
   public static HtmlNode Details     (params IReadOnlyList<HtmlNode> contents) => new HtmlTag(contents, "details"     , CanSelfClose: false);
   public static HtmlNode Dfn         (params IReadOnlyList<HtmlNode> contents) => new HtmlTag(contents, "dfn"         , CanSelfClose: false);
   public static HtmlNode Dialog      (params IReadOnlyList<HtmlNode> contents) => new HtmlTag(contents, "dialog"      , CanSelfClose: false);
   public static HtmlNode Div         (params IReadOnlyList<HtmlNode> contents) => new HtmlTag(contents, "div"         , CanSelfClose: true );
   public static HtmlNode Dl          (params IReadOnlyList<HtmlNode> contents) => new HtmlTag(contents, "dl"          , CanSelfClose: false);
   public static HtmlNode Dt          (params IReadOnlyList<HtmlNode> contents) => new HtmlTag(contents, "dt"          , CanSelfClose: false);
   public static HtmlNode Em          (params IReadOnlyList<HtmlNode> contents) => new HtmlTag(contents, "em"          , CanSelfClose: false);
   public static HtmlNode Embed       (params IReadOnlyList<HtmlNode> contents) => new HtmlTag(contents, "embed"       , CanSelfClose: true );
   public static HtmlNode Fieldset    (params IReadOnlyList<HtmlNode> contents) => new HtmlTag(contents, "fieldset"    , CanSelfClose: false);
   public static HtmlNode Figcaption  (params IReadOnlyList<HtmlNode> contents) => new HtmlTag(contents, "figcaption"  , CanSelfClose: false);
   public static HtmlNode Figure      (params IReadOnlyList<HtmlNode> contents) => new HtmlTag(contents, "figure"      , CanSelfClose: false);
   public static HtmlNode Footer      (params IReadOnlyList<HtmlNode> contents) => new HtmlTag(contents, "footer"      , CanSelfClose: false);
   public static HtmlNode Form        (params IReadOnlyList<HtmlNode> contents) => new HtmlTag(contents, "form"        , CanSelfClose: false);
   public static HtmlNode H1          (params IReadOnlyList<HtmlNode> contents) => new HtmlTag(contents, "h1"          , CanSelfClose: false);
   public static HtmlNode H2          (params IReadOnlyList<HtmlNode> contents) => new HtmlTag(contents, "h2"          , CanSelfClose: false);
   public static HtmlNode H3          (params IReadOnlyList<HtmlNode> contents) => new HtmlTag(contents, "h3"          , CanSelfClose: false);
   public static HtmlNode H4          (params IReadOnlyList<HtmlNode> contents) => new HtmlTag(contents, "h4"          , CanSelfClose: false);
   public static HtmlNode H5          (params IReadOnlyList<HtmlNode> contents) => new HtmlTag(contents, "h5"          , CanSelfClose: false);
   public static HtmlNode H6          (params IReadOnlyList<HtmlNode> contents) => new HtmlTag(contents, "h6"          , CanSelfClose: false);
   public static HtmlNode Head        (params IReadOnlyList<HtmlNode> contents) => new HtmlTag(contents, "head"        , CanSelfClose: false);
   public static HtmlNode Header      (params IReadOnlyList<HtmlNode> contents) => new HtmlTag(contents, "header"      , CanSelfClose: false);
   public static HtmlNode Hgroup      (params IReadOnlyList<HtmlNode> contents) => new HtmlTag(contents, "hgroup"      , CanSelfClose: false);
   public static HtmlNode Hr          (params IReadOnlyList<HtmlNode> contents) => new HtmlTag(contents, "hr"          , CanSelfClose: true );
   public static HtmlNode Html        (params IReadOnlyList<HtmlNode> contents) => new HtmlTag(contents, "html"        , CanSelfClose: false);
   public static HtmlNode I           (params IReadOnlyList<HtmlNode> contents) => new HtmlTag(contents, "i"           , CanSelfClose: false);
   public static HtmlNode Iframe      (params IReadOnlyList<HtmlNode> contents) => new HtmlTag(contents, "iframe"      , CanSelfClose: false);
   public static HtmlNode Img         (params IReadOnlyList<HtmlNode> contents) => new HtmlTag(contents, "img"         , CanSelfClose: true );
   public static HtmlNode Input       (params IReadOnlyList<HtmlNode> contents) => new HtmlTag(contents, "input"       , CanSelfClose: true );
   public static HtmlNode Ins         (params IReadOnlyList<HtmlNode> contents) => new HtmlTag(contents, "ins"         , CanSelfClose: false);
   public static HtmlNode Kbd         (params IReadOnlyList<HtmlNode> contents) => new HtmlTag(contents, "kbd"         , CanSelfClose: false);
   public static HtmlNode Keygen      (params IReadOnlyList<HtmlNode> contents) => new HtmlTag(contents, "keygen"      , CanSelfClose: true );
   public static HtmlNode Label       (params IReadOnlyList<HtmlNode> contents) => new HtmlTag(contents, "label"       , CanSelfClose: false);
   public static HtmlNode Legend      (params IReadOnlyList<HtmlNode> contents) => new HtmlTag(contents, "legend"      , CanSelfClose: false);
   public static HtmlNode Li          (params IReadOnlyList<HtmlNode> contents) => new HtmlTag(contents, "li"          , CanSelfClose: false);
   public static HtmlNode Link        (params IReadOnlyList<HtmlNode> contents) => new HtmlTag(contents, "link"        , CanSelfClose: true );
   public static HtmlNode Main        (params IReadOnlyList<HtmlNode> contents) => new HtmlTag(contents, "main"        , CanSelfClose: false);
   public static HtmlNode Map         (params IReadOnlyList<HtmlNode> contents) => new HtmlTag(contents, "map"         , CanSelfClose: false);
   public static HtmlNode Mark        (params IReadOnlyList<HtmlNode> contents) => new HtmlTag(contents, "mark"        , CanSelfClose: false);
   public static HtmlNode Menu        (params IReadOnlyList<HtmlNode> contents) => new HtmlTag(contents, "menu"        , CanSelfClose: false);
   public static HtmlNode Meta        (params IReadOnlyList<HtmlNode> contents) => new HtmlTag(contents, "meta"        , CanSelfClose: true );
   public static HtmlNode Meter       (params IReadOnlyList<HtmlNode> contents) => new HtmlTag(contents, "meter"       , CanSelfClose: false);
   public static HtmlNode Nav         (params IReadOnlyList<HtmlNode> contents) => new HtmlTag(contents, "nav"         , CanSelfClose: false);
   public static HtmlNode Noscript    (params IReadOnlyList<HtmlNode> contents) => new HtmlTag(contents, "noscript"    , CanSelfClose: false);
   public static HtmlNode Object      (params IReadOnlyList<HtmlNode> contents) => new HtmlTag(contents, "object"      , CanSelfClose: false);
   public static HtmlNode Ol          (params IReadOnlyList<HtmlNode> contents) => new HtmlTag(contents, "ol"          , CanSelfClose: false);
   public static HtmlNode Optgroup    (params IReadOnlyList<HtmlNode> contents) => new HtmlTag(contents, "optgroup"    , CanSelfClose: false);
   public static HtmlNode Option      (params IReadOnlyList<HtmlNode> contents) => new HtmlTag(contents, "option"      , CanSelfClose: false);
   public static HtmlNode Output      (params IReadOnlyList<HtmlNode> contents) => new HtmlTag(contents, "output"      , CanSelfClose: false);
   public static HtmlNode P           (params IReadOnlyList<HtmlNode> contents) => new HtmlTag(contents, "p"           , CanSelfClose: false);
   public static HtmlNode Param       (params IReadOnlyList<HtmlNode> contents) => new HtmlTag(contents, "param"       , CanSelfClose: true );
   public static HtmlNode Picture     (params IReadOnlyList<HtmlNode> contents) => new HtmlTag(contents, "picture"     , CanSelfClose: false);
   public static HtmlNode Pre         (params IReadOnlyList<HtmlNode> contents) => new HtmlTag(contents, "pre"         , CanSelfClose: false);
   public static HtmlNode Progress    (params IReadOnlyList<HtmlNode> contents) => new HtmlTag(contents, "progress"    , CanSelfClose: false);
   public static HtmlNode Q           (params IReadOnlyList<HtmlNode> contents) => new HtmlTag(contents, "q"           , CanSelfClose: false);
   public static HtmlNode Rp          (params IReadOnlyList<HtmlNode> contents) => new HtmlTag(contents, "rp"          , CanSelfClose: false);
   public static HtmlNode Rt          (params IReadOnlyList<HtmlNode> contents) => new HtmlTag(contents, "rt"          , CanSelfClose: false);
   public static HtmlNode Ruby        (params IReadOnlyList<HtmlNode> contents) => new HtmlTag(contents, "ruby"        , CanSelfClose: false);
   public static HtmlNode S           (params IReadOnlyList<HtmlNode> contents) => new HtmlTag(contents, "s"           , CanSelfClose: false);
   public static HtmlNode Samp        (params IReadOnlyList<HtmlNode> contents) => new HtmlTag(contents, "samp"        , CanSelfClose: false);
   public static HtmlNode Script      (params IReadOnlyList<HtmlNode> contents) => new HtmlTag(contents, "script"      , CanSelfClose: false);
   public static HtmlNode Search      (params IReadOnlyList<HtmlNode> contents) => new HtmlTag(contents, "search"      , CanSelfClose: false);
   public static HtmlNode Section     (params IReadOnlyList<HtmlNode> contents) => new HtmlTag(contents, "section"     , CanSelfClose: false);
   public static HtmlNode Select      (params IReadOnlyList<HtmlNode> contents) => new HtmlTag(contents, "select"      , CanSelfClose: false);
   public static HtmlNode Small       (params IReadOnlyList<HtmlNode> contents) => new HtmlTag(contents, "small"       , CanSelfClose: false);
   public static HtmlNode Source      (params IReadOnlyList<HtmlNode> contents) => new HtmlTag(contents, "source"      , CanSelfClose: false);
   public static HtmlNode Span        (params IReadOnlyList<HtmlNode> contents) => new HtmlTag(contents, "span"        , CanSelfClose: false);
   public static HtmlNode Strong      (params IReadOnlyList<HtmlNode> contents) => new HtmlTag(contents, "strong"      , CanSelfClose: false);
   public static HtmlNode Style       (params IReadOnlyList<HtmlNode> contents) => new HtmlTag(contents, "style"       , CanSelfClose: false);
   public static HtmlNode Sub         (params IReadOnlyList<HtmlNode> contents) => new HtmlTag(contents, "sub"         , CanSelfClose: false);
   public static HtmlNode Summary     (params IReadOnlyList<HtmlNode> contents) => new HtmlTag(contents, "summary"     , CanSelfClose: false);
   public static HtmlNode Sup         (params IReadOnlyList<HtmlNode> contents) => new HtmlTag(contents, "sup"         , CanSelfClose: false);
   public static HtmlNode Svg         (params IReadOnlyList<HtmlNode> contents) => new HtmlTag(contents, "svg"         , CanSelfClose: false);
   public static HtmlNode Table       (params IReadOnlyList<HtmlNode> contents) => new HtmlTag(contents, "table"       , CanSelfClose: false);
   public static HtmlNode Tbody       (params IReadOnlyList<HtmlNode> contents) => new HtmlTag(contents, "tbody"       , CanSelfClose: false);
   public static HtmlNode Td          (params IReadOnlyList<HtmlNode> contents) => new HtmlTag(contents, "td"          , CanSelfClose: false);
   public static HtmlNode Template    (params IReadOnlyList<HtmlNode> contents) => new HtmlTag(contents, "template"    , CanSelfClose: false);
   public static HtmlNode Textarea    (params IReadOnlyList<HtmlNode> contents) => new HtmlTag(contents, "textarea"    , CanSelfClose: false);
   public static HtmlNode Tfoot       (params IReadOnlyList<HtmlNode> contents) => new HtmlTag(contents, "tfoot"       , CanSelfClose: false);
   public static HtmlNode Th          (params IReadOnlyList<HtmlNode> contents) => new HtmlTag(contents, "th"          , CanSelfClose: false);
   public static HtmlNode Thead       (params IReadOnlyList<HtmlNode> contents) => new HtmlTag(contents, "thead"       , CanSelfClose: false);
   public static HtmlNode Time        (params IReadOnlyList<HtmlNode> contents) => new HtmlTag(contents, "time"        , CanSelfClose: false);
   public static HtmlNode Title       (params IReadOnlyList<HtmlNode> contents) => new HtmlTag(contents, "title"       , CanSelfClose: false);
   public static HtmlNode Tr          (params IReadOnlyList<HtmlNode> contents) => new HtmlTag(contents, "tr"          , CanSelfClose: false);
   public static HtmlNode Track       (params IReadOnlyList<HtmlNode> contents) => new HtmlTag(contents, "track"       , CanSelfClose: false);
   public static HtmlNode U           (params IReadOnlyList<HtmlNode> contents) => new HtmlTag(contents, "u"           , CanSelfClose: false);
   public static HtmlNode Ul          (params IReadOnlyList<HtmlNode> contents) => new HtmlTag(contents, "ul"          , CanSelfClose: false);
   public static HtmlNode Var         (params IReadOnlyList<HtmlNode> contents) => new HtmlTag(contents, "var"         , CanSelfClose: false);
   public static HtmlNode Video       (params IReadOnlyList<HtmlNode> contents) => new HtmlTag(contents, "video"       , CanSelfClose: false);
   public static HtmlNode Wbr         (params IReadOnlyList<HtmlNode> contents) => new HtmlTag(contents, "wbr"         , CanSelfClose: false);

   public static AttributeNode disabled()             => new BooleanAttributeNode("disabled");
   public static AttributeNode @class  (string value) => new AttributeValueNode  ("class"  , value);
   public static AttributeNode onclick (string value) => new AttributeValueNode  ("onclick", value);
   public static AttributeNode style   (string value) => new AttributeValueNode  ("style"  , value);


   public static HtmlNode Node(string tagName, bool canSelfClose = false, params IReadOnlyList<HtmlNode> contents) => new HtmlTag(contents, tagName, canSelfClose);
   public static AttributeNode boolAttrib(string name) => new BooleanAttributeNode(name);
   public static AttributeNode attrib(string name, string value) => new AttributeValueNode(name, value);
}
